### ISSUE TITLE
how to install?

### ISSUE THREAD

**Issue by bearney74** [aymenfurter/microagents#2]
How do you recommend that we install microagents?

**Comment by bearney74** [comment]
I'm currently using a venv environment for this and got it basically running, except I get an error stating that GPT-4 is not available for me (because I am using a free account for openai):

The model `gpt-4-1106-preview` does not exist or you do not have access to it.

Is there a way we can change the model used?  I assume that the openaiwrapper.py file line 40 is defining this ("text-embedding-ada-002").  Could we make this an environment variable and be able to choose another model?   Is there a model that could be used under a free account?    I have forked your project and I am working on trying to put some of these config settings in a .env file and using dotenv to populate the environment variables.  Plan on pushing a pull request once I get these things implemented and tested.

**Comment by bearney74** [comment]
maybe it would be better to have the embedding portion be a plugin so that we can use different sources (openai, and other AI, or algorithms that are not LLM based)?

**Comment by aymenfurter** [comment]
> How do you recommend that we install microagents?

Thank you for your feedback. Install instructions should be included in the readme file, this is currently missing.

also fair point in making the LLM and embedding model exchangeable.

**Comment by aymenfurter** [comment]
Addressed in the following Pull Request: [PR #6](https://github.com/aymenfurter/microagents/pull/6). This addresses and closes the current issue.

For the model selection, a new issue has been opened: [Issue #5](https://github.com/aymenfurter/microagents/issues/5).
