### ISSUE TITLE
Explanations of how this works and what it is doing

### ISSUE THREAD

**Issue by BSVogler** [aymenfurter/microagents#3]
Hi!
Found this project via HN. The project sounds really interesting. Thank you for sharing.
To make the project more accessible it would benefit from a clearer explanation what it does and how it works.
I found the examples hard to understand. I think it would help a lot of user-input and agent-output would be better differentiated.

The gif is helping a lot but when the last question shows up it loops and you have to watch the whole thing again. I had to take a screenshot in the last milliseconds to read it from the screenshot.
Maybe it is possible to extract the gist of this gif into a text form?

Questions I still have if I have to "construct" the agent pool. Do I have to ask a basic question first so that it generates a basic agent and late I can use it in more complex agents or do I just start with a complex prompt and it does it then automatically.

Happy Holidays
Benedikt

**Comment by aymenfurter** [comment]
Hi Benedikt, 

thanks for your feedback!

I'm working on clearer documentation and better examples. Noted the GIF issue for improvement. For your question, agent pools auto-construct as tasks are divided. Happy Holidays!! 🎁

**Comment by aymenfurter** [comment]
Added to README file, also see: https://raw.githubusercontent.com/aymenfurter/microagents/main/how.png
