### ISSUE TITLE
project requires a paying subscription to openai

### ISSUE THREAD

**Issue by bearney74** [aymenfurter/microagents#4]
It maybe good to state that this project requires a paying subscription to openai to use this project.  This is stated in:

https://platform.openai.com/docs/models/gpt-4-and-gpt-4-turbo

Running the project I got the following error:
2023-12-23 11:19:49,095 - ERROR - OpenAI API error: The model `gpt-4-1106-preview` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.

**Comment by aymenfurter** [comment]
Good point. This should be updated in the readme, agreed.

thank you for your feedback!

**Comment by aymenfurter** [comment]
Addressed in the following pull request: [PR #6](https://github.com/aymenfurter/microagents/pull/6) - Closing issue.
